### ISSUE TITLE
Diff layout is broken

### ISSUE THREAD

**Issue by mkahvi** [Ethaks/FVTT-Quench#132]
It seems to be missing layout rules:  
![Screenshot 2022-05-23 162542](https://user-images.githubusercontent.com/8120158/169829615-907037c1-894d-41c4-8e5e-b8b964a9f863.png)

**Comment by Ethaks** [comment]
Diff display (that is, anything below the error shown in the first line) is somewhat simplistic right now, colouring the differing parts and not doing much else (like splitting results into different lines etc.). The package used for this is [`diff`](https://www.npmjs.com/package/diff). 
So while not particularly flashy, this result is pretty much the expected one. The output for e.g. stringified objects is marginally better than for single-line numbers/strings.

I am quite open about suggestions for improvements though.

**Comment by mkahvi** [comment]
The big issue currently is that it displays them in weird X shape.

|Expected Header|Actual Header|
|---|---|
|Actual Value|Expected Value|

The columns should match at minimum.

**Comment by Ethaks** [comment]
Ah, now I see what you mean. The ordering and/or colouring could definitely be improved a little.

**Comment by Ethaks** [comment]
I slightly tweaked the layout of the header as well as the diff content itself (font colour, context lines):
![diff-layout1](https://user-images.githubusercontent.com/589855/170388339-932ec5e7-af28-44d6-98cb-b7defaf153af.jpg)
![diff-layout2](https://user-images.githubusercontent.com/589855/170388343-71b4de37-073c-4558-8f61-e2b92cb8b484.jpg)

**Comment by mkahvi** [comment]
Please ensure it has sane output when doing a simple test like:
```js
expect(1).to.equal(5);
```
Very artificial, but covers basic number function result testing.

**Comment by Ethaks** [comment]
Since quite a few of those simple equality tests, for which a full-blown diff layout does seem overkill, are to be expected, how about a compact layout specifically for tests whose `expected`/`actual` fit in one line?
![diff-layout3](https://user-images.githubusercontent.com/589855/170509416-8504faea-bb83-486a-a556-436479b4760f.jpg)

The display of the error (containing values) *and* values in the diff is still doubled up, but that does not seem to be unusual amongst test output formats.

**Comment by mkahvi** [comment]
Definitely far better than what it is now.
